apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: khalani-testnet
  namespace: axon
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: testnet.khalani.network
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: axon-chain
                port:
                  number: 8000