---
- name: copy docker .env
  shell: cp -r ../agent/.env.example roles/agent/templates/.env.j2
  tags: copy_config

- name: copy promtail-config.yaml 
  shell: cp -r ../agent/config/promtail/promtail-config.yaml roles/agent/templates/promtail-config.yaml.j2

- name: copy docker-compose
  shell: cp -r ../agent/docker-compose.yml roles/agent/templates/docker-compose.yml.j2
