---
- name: sed env
  shell: sed -i '' 's/LOG_COLLECT_PATH/{{ log_path }}/' roles/agent/templates/.env.j2 && sed -i '' 's/jaeger-collector:14250/192.168.1.2:14250/' roles/agent/templates/.env.j2

- name: sed promtail
  shell: sed -i '' 's/LOKI_ADDRESS/{{ loki_address }}/' roles/agent/templates/promtail-config.yaml.j2

- name: mkdir monitor agent dir
  file: path={{ monitor_dir }}  state=directory mode=0755 recurse=yes

- name: mkdir monitor agent config dir
  file: path={{ monitor_dir }}/config/promtail  state=directory mode=0755 recurse=yes 

- name: copy docker-compose.yml
  template: src=docker-compose.yml.j2 dest={{ monitor_dir }}/docker-compose.yml

- name: copy .env
  template: src=.env.j2 dest={{ monitor_dir }}/.env 

- name: copy promtail-config.yaml
  template: src=promtail-config.yaml.j2 dest={{ monitor_dir }}/config/promtail/promtail-config.yaml

- name: start node-exporter jaeger-agent
  shell: cd {{ monitor_dir }} &&  docker-compose up -d