version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    privileged: true
    shm_size: 16G
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pg_data/data:/var/lib/postgresql/data
