version: '3'

services:
  axon:
    container_name: axon
    build: .
    restart: always
    privileged: true
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ./devtools:/app/devtools
      - ./logs:/app/logs
    networks:
      - axon-net
    command: ./axon -c=/app/devtools/chain/config.toml -g=/app/devtools/chain/genesis.json -m=/app/devtools/chain/nodes/metadata.json

networks:
  axon-net: