<<<<<<< HEAD
<<<<<<< HEAD
enable_access_log: "false"
nginx_port: "8500"


=======
enable_access_log: "true"
=======
enable_access_log: "false"
>>>>>>> 9ce7e55 (nginx disables logging by default)
nginx_port: "8500"
>>>>>>> 8068cf8 (Log modification json format)
