---
- name: axon nginx
  hosts: localhost
  vars_files:
    - config.yml

  tasks:
  ###############################################################################################################

<<<<<<< HEAD
<<<<<<< HEAD
=======
    - name: down
      shell: "docker-compose down"
      ignore_errors: yes
      become: yes
      become_method: sudo
      tags: 
        - down

    - name: start 
      shell: "docker-compose up -d"
      become: yes
      become_method: sudo
      tags: 
        - start

>>>>>>> 8068cf8 (Log modification json format)
=======
>>>>>>> a753e9b (Adjusting the order of deployment tasks)
    - name: Clean axon logs
      file:
        path: ./logs
        state: absent
      become: yes
      become_method: sudo
      tags: 
        - clean

    - name: disable access log.
      when: enable_access_log == 'false'
      replace:
        path: "./nginx/conf/nginx.conf"
        regexp: '(.*access_log.*)'
        replace: '#\1'
      tags: 
        - config

    - name: enable access log.
      when: enable_access_log == 'true'
      replace:
        path: "./nginx/conf/nginx.conf"
        regexp: '^#(.*access_log.*)'
        replace: '\1'
      tags: 
        - config

    - name: Replace nginx port
      replace:
        path: "./docker-compose.yml"
        regexp: "nginx_port"
        replace: "{{ nginx_port }}"
      tags:
        - config
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> a753e9b (Adjusting the order of deployment tasks)

    - name: down
      shell: "docker-compose down"
      ignore_errors: yes
      become: yes
      become_method: sudo
      tags:
        - down

    - name: start
      shell: "docker-compose up -d"
      become: yes
      become_method: sudo
      tags:
        - start
<<<<<<< HEAD
=======
>>>>>>> 8068cf8 (Log modification json format)
=======
>>>>>>> a753e9b (Adjusting the order of deployment tasks)
