---
- name: create muta user
  hosts: muta-dev
  become: true
  tasks:
    - name: create muta user
      user:
        name: "muta"
        groups: docker
        append: yes
    - name: Allow muta to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%muta'
        line: '%muta ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'