---
- name: init chain server
  hosts: muta-dev
  become: true
  tasks:
    - name: install docker, git and pip
      apt:
        name:
          - docker.io
          - git
          - python3-pip
          - python-apt
        update_cache: yes
    - pip:
        name:
          - docker
          - docker-compose
          - ansible
        executable: pip3