---
- name: uni contract
  hosts: localhost
  become: yes
  become_method: sudo
  vars_files:
    - config.yml
    - ../uni-contract-deploy/contract_address.yaml
  tasks:
  ###############################################################################################################
    - name: rm uni-interface
      shell: "rm -rf {{ deploy_path }}"
      become: yes
      become_method: sudo

    - name: mkdir {{ deploy_path }}
      shell: "mkdir -p {{ deploy_path }}"
      become: yes
      become_method: sudo

    - name: Pull code
      git:
        repo: "git://github.com/DavidChild/uniswap_v2.git"
        dest: "{{ deploy_path }}"
        force: yes
      become: yes
      become_method: sudo

    - name: docker-compose
      shell: "cp ./templates/docker-compose.yml {{ deploy_path }}"
      become: yes
      become_method: sudo

    - name: uni-interface shutdown
      shell: "docker-compose -f {{ deploy_path }}/docker-compose.yml down"

    - name: yarn install
      shell: "cd {{ deploy_path }} && sudo yarn install" 
  ###############################################################################################################
    - name: Replace ROUTER_ADDRESS to UniswapV2Router02
      shell: sed -i "s/0x12fE4028b3799420D1C17a09D10EB72b976ec729/{{ UniswapV2Router02 }}/g" "{{ deploy_path }}/src/constants/index.ts"

    - name: Replace `FACTORY_ADDRESS` in the axonuniswapsdk.cjs.development.js with `UniswapV2Factory` 
      shell: sed -i "s/0xc4A3C40808d63e1eE18f7739F239dfA5Bc92bFCd/{{ UniswapV2Factory }}/g" "{{ deploy_path }}/node_modules/axonuniswapsdk/dist/axonuniswapsdk.cjs.development.js"
      
    - name: Replace `WEHT_ADDRESS` in the axonuniswapsdk.cjs.development.js with `WETH` 
      shell: sed -i "s/0xb484fd480E598621638F380F404697Cd9f58B0F8/{{ WETH }}/g" "{{ deploy_path }}/node_modules/axonuniswapsdk/dist/axonuniswapsdk.cjs.development.js"

    - name: Replace `INIT_CODE_HASH` in the axonuniswapsdk.cjs.development.js with `${INIT_CODE_HASH}` 
      shell: sed -i "s/0xfe5c25035eb1580fcbc8496a5d5423870718fac54c9d582b43039dbce6afc72f/{{ InitCodeHash }}/g" "{{ deploy_path }}/node_modules/axonuniswapsdk/dist/axonuniswapsdk.cjs.development.js"

    - name: Replace MuiltiCall_ADDRESS to MuiltiCall
      shell: sed -i "s/0x77787c7473CCd42B815d974f11BcbB1792635082/{{ Multicall }}/g" "{{ deploy_path }}/src/constants/multicall/index.ts"

    - name: Replace  Uniswap start port
      shell: sed -i "s/react-scripts start/PORT={{ PORT }} react-scripts start/g" "{{ deploy_path }}/package.json"
      
###############################################################################################################
    - name: yarn build
      shell: "cd {{ deploy_path }} && yarn build"
      become_method: sudo
      
    - name: yarn start
      shell: "cd {{ deploy_path }} && yarn start"
      become_method: sudo 