apiVersion: v1
kind: Service
metadata:
  labels:
    app: axon4
  name: axon4
  namespace: axon
spec:
  ports:
    - name: p2p
      port: 8001
      targetPort: 8001
      protocol: TCP
    - name: rpc
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: websocket
      port: 8010
      targetPort: 8010
      protocol: TCP
    - name: prometheus
      port: 8100
      targetPort: 8100
      protocol: TCP
  selector:
    app: axon4
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: axon4
  namespace: axon
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  serviceName: "axon4"
  selector:
    matchLabels:
      svc: axon-test
      app: axon4
      logging: "true"
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        svc: axon-test
        app: axon4
        logging: "true"
    spec:
      serviceAccountName: axon-node
      containers:
        - name: axon4
          args:
            - ./axon
            - -c=/app/devtools/chain/k8s/node_4.toml
            - -g=/app/devtools/chain/genesis.json
          image: axonweb3/axon:v0.1.0-beta.1
          env:
            - name: NODE_PRIVATE_KEY_4
              valueFrom:
                secretKeyRef:
                  name: khalani-testnet-nodes-private-keys
                  key: NODE_PRIVATE_KEY_4
          volumeMounts:
          - name: config-node4
            mountPath: /app/devtools/chain/k8s/node_4.toml
            subPath: node_4.toml
          - name: config-genesis
            mountPath: /app/devtools/chain/genesis.json
            subPath: genesis.json
          - name: config-db-options
            mountPath: /app/devtools/chain/k8s/default.db-options
            subPath: default.db-options
          - name: data4
            mountPath: /app/devtools/chain/data4
            subPath: data4
          - name: secrets-store-inline # The volume mount is required for the Sync With Kubernetes Secrets
            mountPath: "/mnt/secrets-store"
            readOnly: true
          ports:
          - name: p2p
            containerPort: 8001
          - name: rpc
            containerPort: 8000
          - name: websocket
            containerPort: 8010
          - name: prometheus
            containerPort: 8100
        - name: jaeger-agent-new
          image: jaegertracing/jaeger-agent:1.32
          env:
          - name: JACGER_COLLECTOR_ADDRESS
            value: jaeger-collector:14250
          - name: JACGER_AGENT_PORT
            value: "6831"
          args: ['--reporter.grpc.host-port=$(JACGER_COLLECTOR_ADDRESS)']
          resources: {}
          securityContext:
            privileged: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingRequiredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node_name
                operator: In
                values:
                - node_4      
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      volumes:
        - name: config-node4
          configMap:
            name: node4-toml
        - name: config-genesis
          configMap:
            name: genesis
        - name: config-db-options
          configMap:
            name: db-options
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "khalani-testnet-nodes-secret-class"
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: data4
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gp2
      resources:
        requests:
          storage: 100Gi
