apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  labels:
    type: local
  name: axon-logs-pv
spec:
  storageClassName: axon-logs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 4Gi
  hostPath:
    path: "./logs"

