apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  labels:
    type: local
  name: axon-logs-pv
  namespace: axon
spec:
  storageClassName: axon-logs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 4Gi
  hostPath:
    path: "/Users/serejke/.axon/logs"
