apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: stable-node-kill
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: all
  selector:
    namespaces:
      - mutadev
    labelSelectors:
      stable-node-kill: "true"
  scheduler:
    cron: "@every 5m"
