apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: stable-network-loss
  namespace: chaos-testing
spec:
  action: loss
  mode: fixed-percent
  value: "30"
  selector:
    namespaces:
      - mutadev
    labelSelectors:
      stable-network-loss: "true"
  loss:
    loss: "25"
    correlation: "25"
  duration: "10s"
  scheduler:
    cron: "@every 1m"
