apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: stable-node-failure
  namespace: chaos-testing
spec:
  action: pod-failure
  mode: fixed-percent
  value: "30"
  duration: "30s"
  selector:
    namespaces:
      - mutadev
    labelSelectors:
      stable-node-failure: "true"
  scheduler:
    cron: "@every 10m"
