# First, create configmap:
# $ kubectl create -n mutadev configmap kubeconfig --from-file=kube.config=~/.kube/config
#
# Then fill in TG_TOKEN and CHAT_ID.

kind: Deployment
apiVersion: apps/v1
metadata:
  name: watchdog
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      name: watchdog
  template:
    metadata:
      labels:
        name: watchdog
    spec:
      containers:
      - name: watchdog
        image: mutadev/watchdog:0.1.17
        resources:
          requests:
            ephemeral-storage: "8Mi"
          limits:
            ephemeral-storage: "1Gi"
        volumeMounts:
            - name: config
              mountPath: /src/config
        env:
          - name: TG_TOKEN
            value: ""
          - name: CHAT_ID
            value: ""
      volumes:
        - name: config
          configMap:
            name: kubeconfig
