apiVersion: v1
kind: PersistentVolume
metadata:
    name: node4-pv-volume
    labels:
        node: node4
spec:
    storageClassName: axon-node-storage-4
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/Users/serejke/.axon/node-4a"
