# crypto
privkey = "NODE_PRIVATE_KEY_2"

# db config
data_path = "./devtools/chain/data2"

# This is unused by Axon.
wckb_contract_address = "0x0000000000000000000000000000000000000000"

[[accounts]]
# KMS key: alias/khalani-axon-key-0
address = "0x1fabea80cc0d328eae0c8f7376935124cf23cc7f"
balance = "04ee2d6d415b85acef8100000000"

[[accounts]]
# KMS key: alias/khalani-axon-key-1
address = "0x78266f4e5590f8f20ac4cbdd15ce479cac64689a"
balance = "04ee2d6d415b85acef8100000000"

[[accounts]]
# KMS key: alias/khalani-axon-key-2
address = "0x1bba69b930b140be5ab7979e556db5a506538020"
balance = "04ee2d6d415b85acef8100000000"

[rpc]
http_listening_address = "0.0.0.0:8000"
ws_listening_address = "0.0.0.0:8010"
maxconn = 25000
max_payload_size = 1048576

[network]
listening_address = "/ip4/0.0.0.0/tcp/8001"
rpc_timeout = 10

[consensus]
sync_txs_chunk_size = 5000

[[network.bootstraps]]
multi_address = "/dns4/axon1/tcp/8001/p2p/QmNk6bBwkLPuqnsrtxpp819XLZY3ymgjs3p1nKtxBVgqxj"

[[network.bootstraps]]
multi_address = "/dns4/axon2/tcp/8001/p2p/QmaHBJqULbLGDn7Td196goNebH6XMTMMu2sKNNP2DiX9S2"

[[network.bootstraps]]
multi_address = "/dns4/axon3/tcp/8001/p2p/QmQLufVVmBuHKoYhdDCqUFYVtLYs1quryoaA1mkQYQdWkn"

[[network.bootstraps]]
multi_address = "/dns4/axon4/tcp/8001/p2p/QmXoSkz4zkHHiFZqmDZQ4gFYtJ72uqtp4m6FX373X4VkRq"

[mempool]
timeout_gap = 20
pool_size = 20000
broadcast_txs_size = 200
broadcast_txs_interval = 200

[executor]
light = false
triedb_cache_size = 500

[logger]
filter = "info"
log_to_console = true
console_show_file_and_line = false
log_path = "logs/node_2/"
log_to_file = true
file_size_limit = 1073741824 # 1 GiB
metrics = true
# you can specify log level for modules with config below
# modules_level = { "overlord::state::process" = "debug", core_consensus = "error" }

[rocksdb]
max_open_files = 64
cache_size = 134217728

# Provide an options file to tune RocksDB for your workload and your system configuration.
# More details can be found in [the official tuning guide](https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide).
options_file = "default.db-options"

[jaeger]
service_name = "axon"
tracing_address = "127.0.0.1:6831"
tracing_batch_size = 50

[prometheus]
listening_address = "0.0.0.0:8100"

[cross_client]
axon_udt_hash = "0xf32ec1e3274c27ac4cc018c92efec443847e9b78ba8cbedca36f0fa8c35d1c9e"
ckb_uri = "https://mercury-testnet.ckbapp.dev/rpc"
mercury_uri = "http://127.0.0.1:8116"
start_block_number = 4096800
checkpoint_interval = 1000
pk = "0x37aa0f893d05914a4def0460c0a984d3611546cfb26924d7a7ca6e0db9950a2d"
enable = false
admin_address = "0x0000000000000000000000000000000000000000"
node_address = "0x0000000000000000000000000000000000000000"
selection_lock_hash = "0xf32ec1e3274c27ac4cc018c92efec443847e9b78ba8cbedca36f0fa8c35d1c9e"
checkpoint_type_hash = "0xf32ec1e3274c27ac4cc018c92efec443847e9b78ba8cbedca36f0fa8c35d1c9e"


[interoperability_extension]
blockchain_extension_transaction_hashes = [
    {name = "cardano", id = 2, tx_hash = "0xb1af175009413bf9670dffb7b120f0eca52896a9798bda123df9b25ff7d8f721"}
]

