# crypto
privkey = "0x4ea4045949bcffdabba4a25c6cf4479a347fc1d7490c5b76f007141604a391df"

# db config
data_path = "./devtools/chain/data/node_2"

wckb_contract_address = "0x0000000000000000000000000000000000000000"

[[accounts]]
address = "0xa0ee7a142d267c1f36714e4a8f75612f20a79720"
balance = "04ee2d6d415b85acef8100000000"

[[accounts]]
address = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"
balance = "04ee2d6d415b85acef8100000000"

[[accounts]]
address = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
balance = "04ee2d6d415b85acef8100000000"

[[accounts]]
address = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
balance = "04ee2d6d415b85acef8100000000"

[[accounts]]
address = "0x90F79bf6EB2c4f870365E785982E1f101E93b906"
balance = "04ee2d6d415b85acef8100000000"

[[accounts]]
address = "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65"
balance = "04ee2d6d415b85acef8100000000"

[[accounts]]
address = "0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc"
balance = "04ee2d6d415b85acef8100000000"

[[accounts]]
address = "0x976EA74026E726554dB657fA54763abd0C3a0aa9"
balance = "04ee2d6d415b85acef8100000000"

[[accounts]]
address = "0x14dC79964da2C08b23698B3D3cc7Ca32193d9955"
balance = "04ee2d6d415b85acef8100000000"

[[accounts]]
address = "0x23618e81E3f5cdF7f54C3d65f7FBc0aBf5B21E8f"
balance = "04ee2d6d415b85acef8100000000"

[rpc]
http_listening_address = "0.0.0.0:8000"
ws_listening_address = "0.0.0.0:8010"
maxconn = 25000
max_payload_size = 1048576

[network]
listening_address = "/ip4/0.0.0.0/tcp/8001"
rpc_timeout = 10

[consensus]
sync_txs_chunk_size = 5000

[[network.bootstraps]]
multi_address = "/dns4/axon4/tcp/8001/p2p/QmcuaTqe3vWVHpjbvKENiADNMRNC49H9Gay1YNfutXQrgA"

[[network.bootstraps]]
multi_address = "/dns4/axon3/tcp/8001/p2p/Qme5e5REPFmQhzRqwniHVSJpkyGwaXAz1akePvX1XEVeci"

[[network.bootstraps]]
multi_address = "/dns4/axon2/tcp/8001/p2p/QmRsnp7rxTQ4PG8SGhWMuwhkkt2SSxjQgpDHSb22dzWh7b"

[[network.bootstraps]]
multi_address = "/dns4/axon1/tcp/8001/p2p/QmUR6FxgPp9HNopT4vyKxkKk2UJf9iMSc7iJHyJiZRVBmZ"

[mempool]
timeout_gap = 20
pool_size = 20000
broadcast_txs_size = 200
broadcast_txs_interval = 200

[executor]
light = false
triedb_cache_size = 500

[logger]
filter = "info"
log_to_console = true
console_show_file_and_line = false
log_path = "logs/node_2/"
log_to_file = true
file_size_limit = 1073741824 # 1 GiB
metrics = true
# you can specify log level for modules with config below
# modules_level = { "overlord::state::process" = "debug", core_consensus = "error" }

[rocksdb]
max_open_files = 64
cache_size = 200
# Provide an options file to tune RocksDB for your workload and your system configuration.
# More details can be found in [the official tuning guide](https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide).
options_file = "default.db-options"
