apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: muta-operator
rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    - secrets
    - nodes
    - pods
    - services
    - resourcequotas
    - replicationcontrollers
    - limitranges
    - persistentvolumeclaims
    - persistentvolumes
    - namespaces
    - endpoints
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
