apiVersion: apps/v1
kind: Deployment
metadata:
  name: muta-operator
  namespace: mutadev
spec:
  replicas: 1
  selector:
    matchLabels:
      name: muta-operator
  template:
    metadata:
      labels:
        name: muta-operator
    spec:
      serviceAccountName: muta-operator
      containers:
        - name: muta-operator
          # Replace this with the built image name
          image: docker.io/mutadev/muta-operator
          command:
          - muta-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "muta-operator"
