kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: muta-operator
  namespace: mutadev
subjects:
- kind: ServiceAccount
  name: muta-operator
  namespace: mutadev
roleRef:
  kind: Role
  name: muta-operator
  apiGroup: rbac.authorization.k8s.io
