version: '3'

services:
  axon:
    container_name: axon-benchmark
    image:  zhengjianhui/axon-benchmark:uniswap
    restart: always
    privileged: true
    volumes:
      - ./config.json:/benchmark/config.json
      - ./state:/benchmark/state
      - ./logs:/benchmark/logs
<<<<<<< HEAD
    command: 'node index.js --benchmark_cases="{\"./uniswapV3_benchmark\": 1}"'
=======
    command: 'node index.js --benchmark_cases="{\"./uniswapV3_benchmark\": 1}"'
>>>>>>> 038be9e (feat: update benchamrk configs)
