name: deploy
on: push

jobs:
  clean_and_deploy_axon:
    name: deploy axon
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Fetch genesis mnemonic from AWS
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids: |
          arn:aws:secretsmanager:us-east-1:803035318642:secret:axon_node_config-VEyMb2
        parse-json-secrets: true

    - name: create axon namespace
      uses: kodermax/kubectl-aws-eks@c18ef8acdb80d5311a7dd3611c57fcc70e954b37
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA}}
      with:
        args: create namespace axon --dry-run=client -o yaml | kubectl apply -f -

    - name: update node1-toml configmap
      uses: kodermax/kubectl-aws-eks@c18ef8acdb80d5311a7dd3611c57fcc70e954b37
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA}}
      with:
        args: create configmap node1-toml --from-file=./k8s-deploy/k8s/axon/axon-config/node_1_template.toml -o yaml --dry-run | sed -e "s/\$MNEMONIC/$MNEMONIC/g" | kubectl apply -n axon -f -

    - name: update node2-toml configmap
      uses: kodermax/kubectl-aws-eks@c18ef8acdb80d5311a7dd3611c57fcc70e954b37
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA}}
      with:
        args: create configmap node2-toml --from-file=./k8s-deploy/k8s/axon/axon-config/node_2.toml -o yaml --dry-run | kubectl apply -n axon -f -

    - name: update node3-toml configmap
      uses: kodermax/kubectl-aws-eks@c18ef8acdb80d5311a7dd3611c57fcc70e954b37
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA}}
      with:
        args: create configmap node3-toml --from-file=./k8s-deploy/k8s/axon/axon-config/node_3.toml -o yaml --dry-run | kubectl apply -n axon -f -

    - name: update node4-toml configmap
      uses: kodermax/kubectl-aws-eks@c18ef8acdb80d5311a7dd3611c57fcc70e954b37
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA}}
      with:
        args: create configmap node4-toml --from-file=./k8s-deploy/k8s/axon/axon-config/node_4.toml -o yaml --dry-run | kubectl apply -n axon -f -

    - name: update genesis configmap
      uses: kodermax/kubectl-aws-eks@c18ef8acdb80d5311a7dd3611c57fcc70e954b37
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA}}
      with:
        args: create configmap genesis --from-file=./k8s-deploy/k8s/axon/axon-config/genesis.json -o yaml --dry-run | kubectl apply -n axon -f -

    - name: update db-options configmap
      uses: kodermax/kubectl-aws-eks@c18ef8acdb80d5311a7dd3611c57fcc70e954b37
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA}}
      with:
        args: create configmap db-options --from-file=./k8s-deploy/k8s/axon/axon-config/default.db-options -o yaml --dry-run | kubectl apply -n axon -f -

    - name: delete axon1
      uses: kodermax/kubectl-aws-eks@c18ef8acdb80d5311a7dd3611c57fcc70e954b37
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA}}
      with:
        args: delete pod axon1-0

    - name: delete axon2
      uses: kodermax/kubectl-aws-eks@c18ef8acdb80d5311a7dd3611c57fcc70e954b37
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA}}
      with:
        args: delete pod axon2-0

    - name: delete axon3
      uses: kodermax/kubectl-aws-eks@c18ef8acdb80d5311a7dd3611c57fcc70e954b37
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA}}
      with:
        args: delete pod axon3-0

    - name: delete axon4
      uses: kodermax/kubectl-aws-eks@c18ef8acdb80d5311a7dd3611c57fcc70e954b37
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA}}
      with:
        args: delete pod axon4-0

    - name: apply axon1
      uses: kodermax/kubectl-aws-eks@c18ef8acdb80d5311a7dd3611c57fcc70e954b37
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA}}
      with:
        args: apply -f ./k8s-deploy/k8s/axon/axon1-statefulset.yaml
        
    - name: apply axon2
      uses: kodermax/kubectl-aws-eks@c18ef8acdb80d5311a7dd3611c57fcc70e954b37
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA}}
      with:
        args: apply -f ./k8s-deploy/k8s/axon/axon2-statefulset.yaml

    - name: apply axon3
      uses: kodermax/kubectl-aws-eks@c18ef8acdb80d5311a7dd3611c57fcc70e954b37
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA}}
      with:
        args: apply -f ./k8s-deploy/k8s/axon/axon3-statefulset.yaml

    - name: apply axon4
      uses: kodermax/kubectl-aws-eks@c18ef8acdb80d5311a7dd3611c57fcc70e954b37
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA}}
      with:
        args: apply -f ./k8s-deploy/k8s/axon/axon4-statefulset.yaml

    - name: apply axon-chain
      uses: kodermax/kubectl-aws-eks@c18ef8acdb80d5311a7dd3611c57fcc70e954b37
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA}}
      with:
        args: apply -f ./k8s-deploy/k8s/axon/axon-chain.yaml
    
    - name: apply axon-ingress
      uses: kodermax/kubectl-aws-eks@c18ef8acdb80d5311a7dd3611c57fcc70e954b37
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA}}
      with:
        args: apply -f ./k8s-deploy/k8s/ingress/axon-ingress.yaml

    - name: apply axon-logs-pv
      uses: kodermax/kubectl-aws-eks@c18ef8acdb80d5311a7dd3611c57fcc70e954b37
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA}}
      with:
        args: apply -f ./k8s-deploy/k8s/pv/axon-logs-pv.yaml

    - name: apply axon-logs-pvc
      uses: kodermax/kubectl-aws-eks@c18ef8acdb80d5311a7dd3611c57fcc70e954b37
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA}}
      with:
        args: apply -f ./k8s-deploy/k8s/pv/axon-logs-pvc.yaml